version: "3.6"
networks:
  farnaa:
    driver: bridge
volumes:
  esdata:
    driver: local
  cache:
    driver: local
    
services:
  elk:
    image: elasticsearch:8.4.2
    container_name: 'farnaa-elasticSearch'
    environment:
    - xpack.security.enabled=false
    - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - IPC_LOCK
    volumes:
    - esdata:/usr/share/elasticsearch/data
    ports:
    - 9200:9200
    - 9300:9300
    networks:
      - farnaa
  kibana:
    container_name: 'farnaa-kibana'
    image: kibana:8.4.2
    environment:
     - ELASTICSEARCH_HOSTS=http://172.19.0.2:9200
    ports:
    - 5601:5601
    depends_on:
    - elk
    networks:
      - farnaa